/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
define([
    //0
     "ace/lib/regexp"
    ,"ace/lib/es5-shim"
    ,"ace/lib/useragent"
    ,"ace/lib/oop"    
    ,"ace/lib/keys"
    ,"ace/lib/dom"
    ,"ace/lib/event"
    ,"ace/lib/lang"
    ,"ace/lib/fixoldbrowsers"
    ,"ace/lib/net"
    ,"ace/token_iterator"
    ,"ace/mode/behaviour"
    ,'ace/undomanager'
    ,"ace/lib/event_emitter"
    ,'ace/keyboard/state_handler'
    ,"ace/mouse/fold_handler"
    ,"ace/tokenizer"
    ,"ace/range"
    ,"ace/range_list"
    ,"ace/unicode"
    ,"ace/mode/xml_util"
    ,"ace/mode/matching_brace_outdent"
    ,"ace/edit_session/fold"
    //1
    ,"ace/keyboard/textinput"
    ,"ace/requirejs/text"
    ,"ace/mouse/default_handlers"
    ,"ace/mouse/default_gutter_handler"
    ,"ace/mouse/mouse_event"
    ,"ace/mouse/dragdrop"
    ,"ace/keyboard/keybinding"
    ,"ace/config"
    ,"ace/anchor"
    ,"ace/mode/text_highlight_rules"
    ,"ace/mode/folding/fold_mode"
    ,"ace/mode/behaviour/cstyle"
    ,"ace/worker/worker_sourcemint"
    ,"ace/background_tokenizer"
    ,"ace/search_highlight" 
    ,"ace/selection"
    ,"ace/edit_session/fold_line"
    ,"ace/edit_session/bracket_match"
    ,"ace/search"
    ,"ace/keyboard/hash_handler"    
    ,"ace/commands/default_commands" 
    ,"ace/layer/gutter"
    ,"ace/layer/marker"
    ,"ace/layer/text"
    ,"ace/layer/cursor"
    ,"ace/scrollbar"
    ,"ace/renderloop"
    //2
    ,'ace/requirejs/text!ace/theme/textmate.css'
    ,"ace/mouse/mouse_handler"
    ,"ace/document"
    ,"ace/mode/text"
    ,"ace/mode/doc_comment_highlight_rules"
    ,"ace/mode/folding/mixed"
    ,"ace/mode/folding/xml"
    ,"ace/mode/folding/cstyle"
    ,"ace/mode/behaviour/xml"
    ,'ace/mode/css_highlight_rules'
    ,"ace/mode/xml_highlight_rules"
    ,"ace/mode/folding/markdown"
    ,"ace/edit_session/folding"  
    ,"ace/commands/command_manager"
    ,'ace/requirejs/text!ace/css/editor.css'
    ,'ace/mode/clojure_highlight_rules'
    ,"ace/mode/folding/coffee"
    ,'ace/mode/coffee_highlight_rules'
    ,"ace/worker/worker_client"
    ,'ace/mode/perl_highlight_rules'  
    ,'ace/mode/python_highlight_rules'    
    //3
    ,'ace/theme/textmate'
    ,"ace/mode/javascript_highlight_rules"
    ,"ace/mode/folding/html"
    ,"ace/mode/behaviour/html"
    ,"ace/mode/xml"
    ,"ace/edit_session"
    ,'ace/virtual_renderer'        
    ,'ace/mode/c_cpp_highlight_rules'
    ,'ace/mode/java_highlight_rules' 
    ,"ace/mode/css"
    //4
    ,'ace/mode/html_highlight_rules'
    ,"ace/mode/javascript"
    //5
    ,'ace/mode/markdown_highlight_rules'
    ,"ace/mode/html"
    //6
    ,'ace/mode/markdown'
    /*,"ace/mode/coffee"
    ,"ace/test/assertions"*/
    /*
    ,'ace/mode/coldfusion_highlight_rules'
    ,'ace/mode/csharp_highlight_rules'
    ,'ace/mode/diff_highlight_rules'
    ,'ace/mode/golang_highlight_rules'
    ,'ace/mode/groovy_highlight_rules'
    ,'ace/mode/haxe_highlight_rules'
    ,'ace/mode/json_highlight_rules'
    ,'ace/mode/jsx_highlight_rules'
    ,'ace/mode/latex_highlight_rules'
    ,'ace/mode/less_highlight_rules'
    ,'ace/mode/liquid_highlight_rules'
    ,'ace/mode/lua_highlight_rules'
    ,'ace/mode/luapage_highlight_rules'
    ,'ace/mode/markdown_highlight_rules'
    ,'ace/mode/ocaml_highlight_rules'
    ,'ace/mode/pgsql_highlight_rules'
    ,'ace/mode/php_highlight_rules'
    ,'ace/mode/powershell_highlight_rules'
    ,'ace/mode/ruby_highlight_rules'
    ,'ace/mode/scad_highlight_rules'
    ,'ace/mode/scala_highlight_rules'
    ,'ace/mode/scss_highlight_rules'
    ,'ace/mode/sh_highlight_rules'
    ,'ace/mode/sql_highlight_rules'
    ,'ace/mode/svg_highlight_rules'
    ,'ace/mode/tcl_highlight_rules'
    ,'ace/mode/textile_highlight_rules'
    ,'ace/mode/xquery_highlight_rules'
    ,'ace/mode/yaml_highlight_rules'
    */
], function() {
  return {};
});

